version: "3.8"

services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-ubuntu
    container_name: my-ubuntu
    volumes:
      - ../:/home/ubuntu
    stdin_open: true
    tty: true
